import { BreedSize, Species } from "@prisma/client";
import type { BreedSeed } from "./breeds";

/**
 * Catalogue mở rộng — các giống phổ biến khác shop nhận đặt cọc tìm bé.
 *
 * Mô tả, hướng dẫn chăm sóc và chỉ số tính cách đều do cửa hàng tự biên soạn.
 * Ảnh nằm trong `frontend/public/breeds`, nguồn ghi ở `src/data/image-credits.ts`.
 *
 * Khoảng giá là mức tham khảo theo thị trường Việt Nam; sửa lại theo giá thật
 * của shop trong trang quản trị hoặc ngay tại đây trước khi chạy seed.
 */
export const EXTRA_BREEDS: BreedSeed[] = [
  // ─────────────────────────── MÈO ───────────────────────────
  {
    name: "Sphynx",
    slug: "sphynx",
    alias: "Mèo không lông",
    description:
      "Không có lông nhưng da ấm như da đào, đôi tai lớn và ánh mắt sâu tạo vẻ ngoài không lẫn vào đâu được. Cực kỳ tình cảm, thích rúc vào người để tìm hơi ấm.",
    species: Species.CAT,
    size: BreedSize.MEDIUM,
    weightRange: "3-5kg",
    priceMin: 20000000,
    priceMax: 50000000,
    image: "/breeds/sphynx-1.jpg",
    images: [
      "/breeds/sphynx-1.jpg",
      "/breeds/sphynx-2.jpg",
      "/breeds/sphynx-3.jpg",
      "/breeds/sphynx-4.jpg",
    ],
    tags: ["Quấn chủ", "hiếu động", "thích hơi ấm"],
    careGuide: [
      "Lau người bằng khăn ẩm 1-2 lần/tuần vì không có lông thấm dầu, da dễ bết.",
      "Giữ nhà đủ ấm và chuẩn bị áo mỏng khi trời lạnh hoặc phòng máy lạnh.",
      "Tránh nắng gắt — da trần rất dễ cháy nắng.",
      "Vệ sinh tai và kẽ móng thường xuyên, hai chỗ này tích dầu nhanh nhất.",
    ],
    suitability:
      "Phù hợp người ở nhà nhiều, thích một bé mèo bám người và không ngại việc lau da định kỳ. Cũng hợp gia đình ngại lông rụng khắp nhà.",
    careNotes:
      "Không có lông không có nghĩa là dễ chăm: da cần lau sạch dầu 1-2 lần/tuần, cần giữ ấm mùa lạnh và che nắng khi ra ngoài.",
    warning: "Da trần dễ cháy nắng và nhiễm lạnh — cần kiểm soát nhiệt độ trong nhà",
    energyLevel: 4,
    apartmentFriendly: 5,
    kidFriendly: 4,
    petFriendly: 4,
    sheddingLevel: 1,
    groomingNeeds: 4,
    trainability: 4,
    barkingLevel: 3,
    position: 12,
  },
  {
    name: "British Longhair",
    slug: "british-longhair",
    alias: "Mèo Anh lông dài",
    description:
      "Cùng gương mặt tròn phúc hậu của mèo Anh nhưng khoác bộ lông dài bồng bềnh. Điềm đạm, ít kêu, thích nằm cạnh chủ hơn là leo trèo.",
    species: Species.CAT,
    size: BreedSize.MEDIUM,
    weightRange: "4-8kg",
    priceMin: 12000000,
    priceMax: 30000000,
    image: "/breeds/british-longhair-1.jpg",
    images: [
      "/breeds/british-longhair-1.jpg",
      "/breeds/british-longhair-2.jpg",
      "/breeds/british-longhair-3.jpg",
      "/breeds/british-longhair-4.jpg",
    ],
    tags: ["Điềm đạm", "quấn chủ", "ít kêu"],
    careGuide: [
      "Chải lông mỗi ngày ở vùng nách, bẹn và yếm cổ — ba chỗ rối trước tiên.",
      "Tắm định kỳ 4-6 tuần/lần, sấy khô hoàn toàn để tránh nấm da.",
      "Dùng thức ăn kiểm soát búi lông vì bé nuốt nhiều lông khi tự liếm.",
      "Cân bé hằng tháng, giống này lười vận động và rất dễ tăng cân.",
    ],
    suitability:
      "Phù hợp gia đình thích một bé mèo trầm tính, hợp căn hộ, và có 5-10 phút mỗi ngày để chải lông.",
    careNotes:
      "Bộ lông dài cần chải mỗi ngày để không bết; nên có thức ăn kiểm soát búi lông và theo dõi cân nặng.",
    energyLevel: 2,
    apartmentFriendly: 5,
    kidFriendly: 5,
    petFriendly: 4,
    sheddingLevel: 4,
    groomingNeeds: 4,
    trainability: 3,
    barkingLevel: 1,
    position: 13,
  },
  {
    name: "Highland Fold",
    slug: "highland-fold",
    alias: "Mèo tai cụp lông dài",
    description:
      "Phiên bản lông dài của Scottish Fold: vẫn đôi tai cụp về trước và gương mặt tròn như cú mèo, nhưng khoác thêm lớp lông bồng bềnh mềm mại.",
    species: Species.CAT,
    size: BreedSize.MEDIUM,
    weightRange: "3-6kg",
    priceMin: 15000000,
    priceMax: 30000000,
    image: "/breeds/highland-fold-1.jpg",
    images: [
      "/breeds/highland-fold-1.jpg",
      "/breeds/highland-fold-2.jpg",
      "/breeds/highland-fold-3.jpg",
      "/breeds/highland-fold-4.jpg",
    ],
    tags: ["Hiền lành", "thích ôm ấp", "nhẹ nhàng"],
    careGuide: [
      "Chải lông mỗi ngày, chú ý vùng sau tai vì tai cụp che khuất dễ bỏ sót.",
      "Vệ sinh tai nhẹ nhàng mỗi tuần — tai cụp giữ ẩm nên dễ viêm hơn tai thẳng.",
      "Theo dõi khớp và dáng đi định kỳ, đặc biệt từ 2-3 tuổi trở đi.",
      "Bố trí bậc thấp lên giường, sofa để bé không phải nhảy cao.",
    ],
    suitability:
      "Phù hợp gia đình thích ôm ấp, sống ở nơi ổn định và sẵn sàng đưa bé khám khớp định kỳ.",
    careNotes:
      "Chải lông hằng ngày và vệ sinh tai hằng tuần; khám khớp định kỳ vì gen tai cụp ảnh hưởng tới sụn.",
    warning: "Gen tai cụp có thể ảnh hưởng sụn khớp — cần khám định kỳ",
    energyLevel: 2,
    apartmentFriendly: 5,
    kidFriendly: 5,
    petFriendly: 4,
    sheddingLevel: 4,
    groomingNeeds: 4,
    trainability: 3,
    barkingLevel: 2,
    position: 14,
  },
  {
    name: "Munchkin Fold",
    slug: "munchkin-fold",
    alias: "Mèo chân ngắn tai cụp",
    description:
      "Kết hợp chân ngắn của Munchkin với đôi tai cụp đặc trưng. Dáng đi lạch bạch chậm rãi, gương mặt lúc nào cũng như đang ngơ ngác đòi bế.",
    species: Species.CAT,
    size: BreedSize.SMALL,
    weightRange: "2.5-4kg",
    priceMin: 18000000,
    priceMax: 35000000,
    image: "/breeds/munchkin-fold-1.jpg",
    images: [
      "/breeds/munchkin-fold-1.jpg",
      "/breeds/munchkin-fold-2.jpg",
      "/breeds/munchkin-fold-3.jpg",
    ],
    tags: ["Ngoan ngoãn", "bám người", "tò mò"],
    careGuide: [
      "Hạn chế để bé nhảy từ độ cao lớn — chân ngắn cộng cột sống dài là điểm yếu.",
      "Ưu tiên đồ chơi chơi được ở mặt đất thay vì kệ leo cao.",
      "Vệ sinh tai nhẹ nhàng mỗi tuần vì tai cụp dễ giữ ẩm.",
      "Khám cột sống và khớp mỗi lần đi kiểm tra sức khoẻ định kỳ.",
    ],
    suitability:
      "Phù hợp người thích một bé mèo nhỏ, bám người, sống trong căn hộ và chấp nhận bố trí lại nhà cho bé đỡ phải nhảy cao.",
    careNotes:
      "Bé mang hai đặc điểm di truyền cần theo dõi: chân ngắn ảnh hưởng cột sống, tai cụp ảnh hưởng sụn khớp. Khám định kỳ là bắt buộc.",
    warning: "Vừa chân ngắn vừa tai cụp — cần khám cột sống và khớp định kỳ",
    energyLevel: 3,
    apartmentFriendly: 5,
    kidFriendly: 4,
    petFriendly: 4,
    sheddingLevel: 3,
    groomingNeeds: 3,
    trainability: 3,
    barkingLevel: 2,
    position: 15,
  },

  // ─────────────────────────── CHÓ ───────────────────────────
  {
    name: "Maltese",
    slug: "maltese",
    alias: "Chó Malta",
    description:
      "Bộ lông trắng dài buông thẳng như tơ, thân hình nhỏ nhắn cân đối. Tình cảm, quấn chủ và thích được ở gần người cả ngày.",
    species: Species.DOG,
    size: BreedSize.SMALL,
    weightRange: "3-4kg",
    priceMin: 8000000,
    priceMax: 20000000,
    image: "/breeds/maltese-1.jpg",
    images: [
      "/breeds/maltese-1.jpg",
      "/breeds/maltese-2.jpg",
      "/breeds/maltese-3.jpg",
      "/breeds/maltese-4.jpg",
    ],
    tags: ["Quấn chủ", "thân thiện", "cảnh giác"],
    careGuide: [
      "Chải lông mỗi ngày nếu để lông dài; cắt ngắn kiểu puppy cut thì nhẹ hơn nhiều.",
      "Lau vùng quanh mắt hằng ngày vì lông trắng rất dễ lộ vệt nước mắt.",
      "Cắt tỉa mỗi 4-6 tuần, đặc biệt gọn vùng bàn chân và hậu môn.",
      "Tập cho bé quen ở một mình từ nhỏ để tránh lo âu chia ly.",
    ],
    suitability:
      "Phù hợp căn hộ và người sống một mình hoặc gia đình ít vận động, thích một bé chó nhỏ luôn ở bên cạnh.",
    careNotes:
      "Lông trắng dài cần chải mỗi ngày và lau vùng mắt thường xuyên; bé khá bám người nên không hợp nhà vắng cả ngày.",
    energyLevel: 3,
    apartmentFriendly: 5,
    kidFriendly: 3,
    petFriendly: 4,
    sheddingLevel: 1,
    groomingNeeds: 5,
    trainability: 4,
    barkingLevel: 4,
    position: 16,
  },
  {
    name: "Pomeranian",
    slug: "pomeranian",
    alias: "Phốc sóc",
    description:
      "Nhỏ như cục bông nhưng tự tin hơn kích thước rất nhiều. Bộ lông kép dày dựng đứng quanh cổ, gương mặt lanh lợi như cáo con.",
    species: Species.DOG,
    size: BreedSize.SMALL,
    weightRange: "2-3.5kg",
    priceMin: 6000000,
    priceMax: 15000000,
    image: "/breeds/pomeranian-1.jpg",
    images: [
      "/breeds/pomeranian-1.jpg",
      "/breeds/pomeranian-2.jpg",
      "/breeds/pomeranian-3.jpg",
      "/breeds/pomeranian-4.jpg",
    ],
    tags: ["Lanh lợi", "dũng cảm", "quấn chủ"],
    careGuide: [
      "Chải lông 3-4 lần/tuần, tăng lên hằng ngày trong mùa thay lông.",
      "Không cạo sát lông — lớp lông kép có tác dụng cách nhiệt cả nóng lẫn lạnh.",
      "Vệ sinh răng đều đặn, giống nhỏ rất dễ bị bệnh răng miệng sớm.",
      "Dạy lệnh im lặng từ nhỏ vì bé có xu hướng sủa báo động nhiều.",
    ],
    suitability:
      "Phù hợp căn hộ và người thích một bé chó nhỏ nhưng cá tính. Cân nhắc nếu chung cư có quy định nghiêm về tiếng ồn.",
    careNotes:
      "Lông kép cần chải 3-4 lần/tuần và không nên cạo sát; nên chăm răng sớm và tập giảm sủa từ nhỏ.",
    warning: "Xương khớp nhỏ, dễ trật xương bánh chè — hạn chế nhảy từ trên cao",
    energyLevel: 4,
    apartmentFriendly: 5,
    kidFriendly: 3,
    petFriendly: 3,
    sheddingLevel: 4,
    groomingNeeds: 4,
    trainability: 4,
    barkingLevel: 5,
    position: 17,
  },
  {
    name: "Dachshund",
    slug: "dachshund",
    alias: "Chó lạp xưởng",
    description:
      "Thân dài, chân ngắn và đôi tai to rủ xuống. Vốn là giống chó săn nên bé dũng cảm, bền bỉ và có khứu giác rất nhạy.",
    species: Species.DOG,
    size: BreedSize.SMALL,
    weightRange: "5-14kg",
    priceMin: 5000000,
    priceMax: 12000000,
    image: "/breeds/dachshund-1.jpg",
    images: [
      "/breeds/dachshund-1.jpg",
      "/breeds/dachshund-2.jpg",
      "/breeds/dachshund-3.jpg",
      "/breeds/dachshund-4.jpg",
    ],
    tags: ["Dũng cảm", "trung thành", "lanh lợi"],
    careGuide: [
      "Tuyệt đối hạn chế nhảy từ ghế, giường xuống — dùng dốc thoải nếu bé hay lên sofa.",
      "Bế bằng cách đỡ cả ngực và mông, không bao giờ nhấc bằng hai nách.",
      "Giữ cân nặng chuẩn, mỗi cân thừa là thêm áp lực lên cột sống.",
      "Vệ sinh tai rủ định kỳ để tránh ẩm và viêm.",
    ],
    suitability:
      "Phù hợp gia đình ở nhà mặt đất hoặc căn hộ có thể bố trí dốc, chấp nhận theo dõi cột sống cho bé suốt đời.",
    careNotes:
      "Cột sống là điểm yếu lớn nhất: hạn chế nhảy cao, kiểm soát cân nặng và bế đúng cách.",
    warning: "Bệnh đĩa đệm rất phổ biến ở giống này — hạn chế nhảy và giữ cân chuẩn",
    energyLevel: 4,
    apartmentFriendly: 4,
    kidFriendly: 3,
    petFriendly: 3,
    sheddingLevel: 3,
    groomingNeeds: 2,
    trainability: 3,
    barkingLevel: 4,
    position: 18,
  },
  {
    name: "Chow Chow",
    slug: "chow-chow",
    alias: "Chó sư tử",
    description:
      "Bộ lông xù dày như bờm sư tử, dáng đi vững chãi và chiếc lưỡi xanh đen độc nhất. Độc lập, trầm tính, trung thành với riêng gia đình mình.",
    species: Species.DOG,
    size: BreedSize.LARGE,
    weightRange: "20-32kg",
    priceMin: 15000000,
    priceMax: 40000000,
    image: "/breeds/chow-chow-1.jpg",
    images: [
      "/breeds/chow-chow-1.jpg",
      "/breeds/chow-chow-2.jpg",
      "/breeds/chow-chow-3.jpg",
      "/breeds/chow-chow-4.jpg",
    ],
    tags: ["Độc lập", "trung thành", "trầm tính"],
    careGuide: [
      "Chải lông 3-4 lần/tuần quanh năm, hằng ngày trong mùa thay lông.",
      "Cần phòng mát và đủ nước mùa hè — bộ lông dày khiến bé rất dễ sốc nhiệt.",
      "Xã hội hoá kỹ từ nhỏ vì bé khá dè chừng người lạ.",
      "Kiểm tra mắt định kỳ, giống này dễ gặp các vấn đề về mí mắt.",
    ],
    suitability:
      "Phù hợp gia đình có kinh nghiệm nuôi chó lớn, không gian mát mẻ và thời gian xã hội hoá cho bé từ nhỏ. Không hợp người nuôi chó lần đầu.",
    careNotes:
      "Bộ lông cực dày cần chải 3-4 lần/tuần và nơi ở mát mẻ; tính cách độc lập đòi hỏi chủ kiên nhẫn và xã hội hoá sớm.",
    warning: "Rất dễ sốc nhiệt mùa hè Việt Nam — cần phòng mát và tránh nắng",
    energyLevel: 2,
    apartmentFriendly: 2,
    kidFriendly: 3,
    petFriendly: 2,
    sheddingLevel: 5,
    groomingNeeds: 5,
    trainability: 2,
    barkingLevel: 2,
    position: 19,
  },
  {
    name: "Bichon Frise",
    slug: "bichon-frise",
    alias: "Chó bông gòn",
    description:
      "Bộ lông xoăn trắng bồng bềnh như cục bông, gần như không rụng. Vui vẻ, hoà đồng và gắn bó với mọi thành viên trong nhà.",
    species: Species.DOG,
    size: BreedSize.SMALL,
    weightRange: "5-8kg",
    priceMin: 10000000,
    priceMax: 25000000,
    image: "/breeds/bichon-frise-1.jpg",
    images: [
      "/breeds/bichon-frise-1.jpg",
      "/breeds/bichon-frise-2.jpg",
      "/breeds/bichon-frise-3.jpg",
      "/breeds/bichon-frise-4.jpg",
    ],
    tags: ["Vui vẻ", "hoà đồng", "thân thiện"],
    careGuide: [
      "Chải 3-4 lần/tuần: lông xoăn không rụng ra ngoài mà mắc lại trong bộ lông và bết rất nhanh.",
      "Cắt tỉa mỗi 4-6 tuần để giữ dáng bông tròn đặc trưng.",
      "Lau vùng quanh mắt hằng ngày vì lông trắng dễ lộ vệt nước mắt.",
      "Theo dõi da — giống này hay bị dị ứng da và ngứa.",
    ],
    suitability:
      "Phù hợp gia đình có trẻ nhỏ, người sống căn hộ, và ai ngại lông rụng nhưng chấp nhận chi phí cắt tỉa định kỳ.",
    careNotes:
      "Không rụng lông nhưng cần chải 3-4 lần/tuần và cắt tỉa mỗi 4-6 tuần; chú ý các vấn đề da liễu.",
    energyLevel: 4,
    apartmentFriendly: 5,
    kidFriendly: 5,
    petFriendly: 5,
    sheddingLevel: 1,
    groomingNeeds: 5,
    trainability: 4,
    barkingLevel: 3,
    position: 20,
  },
  {
    name: "Labrador Retriever",
    slug: "labrador-retriever",
    alias: "Chó Labrador",
    description:
      "Thân hình săn chắc, ánh mắt hiền và tính cách hoà nhã đúng chuẩn chó gia đình. Thông minh, dễ huấn luyện và cực kỳ kiên nhẫn với trẻ em.",
    species: Species.DOG,
    size: BreedSize.LARGE,
    weightRange: "25-36kg",
    priceMin: 8000000,
    priceMax: 20000000,
    image: "/breeds/labrador-retriever-1.jpg",
    images: [
      "/breeds/labrador-retriever-1.jpg",
      "/breeds/labrador-retriever-2.jpg",
      "/breeds/labrador-retriever-3.jpg",
      "/breeds/labrador-retriever-4.jpg",
    ],
    tags: ["Hiền lành", "thông minh", "trung thành"],
    careGuide: [
      "Cần vận động mạnh ít nhất 60 phút mỗi ngày; bé rất thích bơi và tha đồ.",
      "Kiểm soát khẩu phần chặt chẽ — giống này ăn khoẻ và dễ béo phì bậc nhất.",
      "Chải lông 2-3 lần/tuần, lông ngắn nhưng rụng đều quanh năm.",
      "Kiểm tra tai định kỳ vì tai cụp dễ giữ ẩm gây viêm.",
    ],
    suitability:
      "Phù hợp gia đình có sân vườn hoặc gần công viên, có thời gian vận động cùng bé mỗi ngày; rất hợp nhà có trẻ nhỏ.",
    careNotes:
      "Cần vận động nhiều và kiểm soát khẩu phần nghiêm ngặt; béo phì là vấn đề phổ biến nhất của giống này.",
    warning: "Rất dễ béo phì và có nguy cơ loạn sản khớp háng — cần cân đúng khẩu phần",
    energyLevel: 5,
    apartmentFriendly: 2,
    kidFriendly: 5,
    petFriendly: 5,
    sheddingLevel: 4,
    groomingNeeds: 2,
    trainability: 5,
    barkingLevel: 3,
    position: 21,
  },
  {
    name: "Cardigan Welsh Corgi",
    slug: "cardigan-welsh-corgi",
    alias: "Corgi có đuôi",
    description:
      "Người anh em cổ hơn của Pembroke, khác biệt ở chiếc đuôi dài như đuôi cáo và khung xương to chắc hơn. Điềm đạm, chín chắn và bình tĩnh hơn.",
    species: Species.DOG,
    size: BreedSize.MEDIUM,
    weightRange: "11-17kg",
    priceMin: 15000000,
    priceMax: 35000000,
    image: "/breeds/cardigan-welsh-corgi-1.jpg",
    images: [
      "/breeds/cardigan-welsh-corgi-1.jpg",
      "/breeds/cardigan-welsh-corgi-2.jpg",
      "/breeds/cardigan-welsh-corgi-3.jpg",
      "/breeds/cardigan-welsh-corgi-4.jpg",
    ],
    tags: ["Điềm đạm", "chín chắn", "trung thành"],
    careGuide: [
      "Hạn chế nhảy từ trên cao xuống để bảo vệ cột sống, giống mọi giống thân dài chân ngắn.",
      "Vận động đều 30-45 phút mỗi ngày, bé vốn là chó chăn gia súc nên cần việc để làm.",
      "Chải lông 2-3 lần/tuần, nhiều hơn trong mùa thay lông.",
      "Giữ cân nặng chuẩn để giảm áp lực lên lưng và khớp.",
    ],
    suitability:
      "Phù hợp gia đình muốn nét Corgi nhưng thích tính cách điềm tĩnh hơn, có không gian và thời gian vận động cùng bé mỗi ngày.",
    careNotes:
      "Cần vận động 30-45 phút/ngày và hạn chế nhảy cao; rụng lông theo mùa khá nhiều nên phải chải đều.",
    warning: "Thân dài chân ngắn — cần cẩn thận cột sống như mọi dòng Corgi",
    energyLevel: 4,
    apartmentFriendly: 3,
    kidFriendly: 4,
    petFriendly: 4,
    sheddingLevel: 4,
    groomingNeeds: 3,
    trainability: 4,
    barkingLevel: 3,
    position: 22,
  },
];
